'use client';

import { useMemo } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { useSetAtom } from 'jotai';
import { Card } from './ui/card';
import { Button } from './ui/button';
import { importPortfolioAtom } from '@/store/persistedPortfolioAtom';
import type { PersistedPortfolio, PersistedStock } from '@/lib/types';
import { Download, X } from 'lucide-react';

interface ImportedPortfolioData {
  name: string;
  stocks: PersistedStock[];
}

type ParseResult =
  | { type: 'none' }
  | { type: 'error'; message: string }
  | { type: 'success'; data: ImportedPortfolioData };

function isValidImportData(data: unknown): data is ImportedPortfolioData {
  if (typeof data !== 'object' || data === null) return false;
  const obj = data as Record<string, unknown>;

  if (typeof obj.name !== 'string') return false;
  if (!Array.isArray(obj.stocks)) return false;

  return obj.stocks.every(
    (stock: unknown) =>
      typeof stock === 'object' &&
      stock !== null &&
      typeof (stock as Record<string, unknown>).ticker === 'string' &&
      typeof (stock as Record<string, unknown>).name === 'string' &&
      typeof (stock as Record<string, unknown>).shares === 'number' &&
      typeof (stock as Record<string, unknown>).currency === 'string'
  );
}

function parseImportParam(importParam: string | null): ParseResult {
  if (!importParam) {
    return { type: 'none' };
  }

  try {
    const decoded = atob(importParam);
    const parsed = JSON.parse(decoded);

    if (!isValidImportData(parsed)) {
      return { type: 'error', message: 'Invalid portfolio data' };
    }

    return { type: 'success', data: parsed };
  } catch {
    return { type: 'error', message: 'Failed to decode portfolio data' };
  }
}

export function PortfolioImportDialog() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const importPortfolio = useSetAtom(importPortfolioAtom);

  const parseResult = useMemo(
    () => parseImportParam(searchParams.get('import')),
    [searchParams]
  );

  const handleImport = () => {
    if (parseResult.type !== 'success') return;

    const portfolio: PersistedPortfolio = {
      id: '', // Will be generated by the atom
      name: parseResult.data.name,
      stocks: parseResult.data.stocks,
    };

    importPortfolio(portfolio);
    clearImportParam();
  };

  const handleCancel = () => {
    clearImportParam();
  };

  const clearImportParam = () => {
    const url = new URL(window.location.href);
    url.searchParams.delete('import');
    router.replace(url.pathname + url.search);
  };

  if (parseResult.type === 'none') return null;

  return (
    <div
      className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
      onClick={handleCancel}
    >
      <Card
        className="w-full max-w-md p-6"
        onClick={(e) => e.stopPropagation()}
      >
        {parseResult.type === 'error' ? (
          <>
            <div className="flex items-center gap-2 text-destructive mb-4">
              <X className="w-5 h-5" />
              <h3 className="font-semibold">Import Error</h3>
            </div>
            <p className="text-sm text-muted-foreground mb-4">{parseResult.message}</p>
            <Button onClick={handleCancel} className="w-full">
              Close
            </Button>
          </>
        ) : (
          <>
            <div className="flex items-center gap-2 mb-4">
              <Download className="w-5 h-5 text-primary" />
              <h3 className="font-semibold">Import Portfolio</h3>
            </div>

            <div className="mb-4">
              <p className="text-sm text-muted-foreground mb-2">
                Someone shared a portfolio with you:
              </p>
              <div className="bg-muted rounded-md p-3">
                <p className="font-medium">{parseResult.data.name}</p>
                <p className="text-sm text-muted-foreground">
                  {parseResult.data.stocks.length} stock
                  {parseResult.data.stocks.length !== 1 ? 's' : ''}
                </p>
              </div>
            </div>

            {parseResult.data.stocks.length > 0 && (
              <div className="mb-4 max-h-40 overflow-y-auto">
                <p className="text-xs text-muted-foreground mb-2">Stocks:</p>
                <div className="space-y-1">
                  {parseResult.data.stocks.map((stock) => (
                    <div
                      key={stock.ticker}
                      className="flex items-center justify-between text-sm"
                    >
                      <span className="font-mono">{stock.ticker}</span>
                      <span className="text-muted-foreground">
                        {stock.shares} shares
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="flex gap-2">
              <Button onClick={handleImport} className="flex-1">
                <Download className="w-4 h-4 mr-2" />
                Import
              </Button>
              <Button variant="outline" onClick={handleCancel} className="flex-1">
                Cancel
              </Button>
            </div>
          </>
        )}
      </Card>
    </div>
  );
}
